CREATE TABLE teams
(
teamID INT AUTO_INCREMENT PRIMARY KEY,
teamName CHAR(40) NOT NULL,
startYear INT(4) NOT NULL,
ownerName VARCHAR(255) NOT NULL,
GMName VARCHAR(255) NOT NULL,
coachName VARCHAR(255) NOT NULL,
MVP VARCHAR(255) NOT NULL,
arenaAddress VARCHAR(255) NOT NULL,
city CHAR(50) NOT NULL,
state CHAR(20) NOT NULL,
zipCode INT(5) NOT NULL,
phone INT(10) NOT NULL,
divRecord VARCHAR(15) NOT NULL,
confRecord VARCHAR (15) NOT NULL
);
